spring.application.name=get-a-record_API
lastfm.api.key=${LASTFM_API_KEY}
lastfm.api.sharedSecret=${LASTFM_API_SHAREDSECRET:defaultvalue}
lastfm.api.baseUrl=${LASTFM_API_BASEURL}

#Burial
artist.mbid.defaultValue=9ddce51c-2b75-4b3e-ac8c-1db09e7c89c6
#Burial - Untrue
album.mbid.defaultValue=02aa03a5-001b-4e5a-b3ad-23ad0fadb49c